# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Curio
    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Change directory
      run: cd ./Curio/
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - name: Make envfile
      uses: SpicyPizza/create-envfile@v2.0
      with:
        envkey_VITE_CLIENT_ID: ${{ secrets.VITE_CLIENT_ID }}
        envkey_VITE_CLIENT_SECRET: ${{ secrets.VITE_CLIENT_SECRET }}
        envkey_VITE_SERVER_HOST: ${{ secrets.VITE_SERVER_HOST }}
        file_name: .env
        fail_on_empty: true
        sort_keys: false
    - run: npm run build --if-present
    - run: npm run test
