# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Curio
    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: listing files
      run: ls 
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache-dependency-path: './Curio'
        cache: 'npm'
    - run: npm ci
    - name: Make envfile
      uses: SpicyPizza/create-envfile@v2.0
      with:
        envkey_VITE_CLIENT_ID: ${{ secrets.VITE_CLIENT_ID }}
        envkey_VITE_CLIENT_SECRET: ${{ secrets.VITE_CLIENT_SECRET }}
        envkey_VITE_SERVER_HOST: ${{ secrets.VITE_SERVER_HOST }}
        directory: ./Curio
        file_name: .env
        fail_on_empty: true
        sort_keys: false
    - name: debugging .env
      run: cat .env 
    - run: npm run test
    - name: Send mail
      if: failure()
      uses: dawidd6/action-send-mail@v2
      with:
        # mail server settings
        server_address: smtp.gmail.com
        server_port: 465
        # user credentials
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        # email subject
        subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}
        # email body as text
        body: ${{ github.job }} job in worflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }}
        # comma-separated string, send email to
        to: Omar.Abdelazim02@eng-st.cu.edu.eg
        # from email name
        from: ali.abdelmaguid02@eng-st.cu.edu.eg
    - name: listing files
      run: ls 
    - name: Deleting node_modules
      #This is deleted since we dont want to copy the node_modules into the dcoker container
      run: rm -r node_modules
    - name: Build & push Docker image
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        image: isslolo/curio
        tags: curio-frontend
        dockerfile: ./Curio/Dockerfile
        directory: ./Curio
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Azure CLI script
      uses: azure/cli@v2
      with:
        azcliversion: latest
        inlineScript: |
          az vm run-command invoke -g CurioT7 -n CurioT7 --command-id RunShellScript --scripts "/home/azureuser/curio/deploy.sh "

